### PR TITLE
Fixed error summary broken links

### PR DESCRIPTION
**Pull request by jmsatheesh**
# Pull Request Checklist
- Add/update Welsh translation if required.
- Add any logging needed for Bridge Team monitoring.
- Add unit/acceptance/performance tests for new features.
- Make sure code coverage has not dropped.
- Run the [tamc-acceptance-tests](https://github.com/hmrc/tamc-acceptance-tests).
- Run the [tamc-performance-tests](https://github.com/hmrc/tamc-performance-tests).
- Perform relevant accessibility checks.
- Test manually in browser if required.
- Make any environment configuration changes/checks if needed.

### CODE REVIEW

**Comment by vinnicombe** [comment]
The solution is not correct. You have amended the form to fit the error link, when you should be amending the error link to correctly locate to the first radio button.

**Review by vinnicombe — CHANGES_REQUESTED** [review]
See comment. You need to change the key returned in the form validation here: https://github.com/hmrc/tamc-frontend/blob/main/app/forms/EligibilityCalculatorForm.scala#L78

**Comment by jmsatheesh** [comment]
> See comment. You need to change the key returned in the form validation here: https://github.com/hmrc/tamc-frontend/blob/main/app/forms/EligibilityCalculatorForm.scala#L78

Fixed

**Review by vinnicombe — APPROVED** [review]
LGTM

**Pull request merged**
